### ISSUE TITLE
What important features are not yet implemented in JSoar 0.14.9 vs. CSoar 9.6.0?

### ISSUE THREAD

**Issue by heikefn** [soartech/jsoar#117]
I'm learning JSoar recently and I'm having some problems.Because Jsoar continues to improve, in order to realize Csoar has the function, is so far and I care more about our existing Jsoar source and implementation has achieved Csoar whether all the kernel program, I worry about using Jsoar, some functions in Jsoar Csoar no, so, can you tell me about contrast Csoar version 9.6 and what part does not implement?

Thank you. Looking forward to your reply.

**Comment by marinier** [comment]
Hi,

You are correct, jsoar is behind csoar in terms of functionality in most ways (although jsoar has some features csoar doesn’t have as well).

The major missing features at this point are SVS and the new version of chunking released in 9.6.0. The commands were also refactored in 9.6.0 – this change will be in the next release of jsoar (probably in the next month).

Some of the features that jsoar has may be incomplete or missing the most recent changes. In particular, many of the less commonly used commands and command options are missing. Probably the closest version of csoar is 9.3.4. Changes to things like smem, epmem, WMA, RL, etc. since then may not be reflected in jsoar (but we don’t track the releases – we port features as needed or as resources allow).

You may be able to get a better sense of the state of things from the changelog:

https://github.com/soartech/jsoar/wiki/ChangeLog

Bob
