### ISSUE TITLE
Support multiple instances of debugger widgets

### ISSUE THREAD

**Issue by voigtjr** [soartech/jsoar#2]
Reported by project member @daveray, Dec 3, 2008
Add support for creating multiple instances of (select?) debugger widgets. 

This will require some thought about selection management. See Debugger
(http://groups.google.com/group/jsoar-dev/browse_thread/thread/1d918796e568d6e6)
discussion on jsoar-dev.

**Comment by marinier** [comment]
The debugger recently got a new "stop" widget (which is actually broken) that supports multiple instances. It's broken because of some kind of threading issue, but the basic idea of multiple widget instances has been demonstrated. Current widgets would need changes to support this, but we'd want to think carefully about whether it's actually worth it (e.g., there would probably be major performance impacts from having multiple trace widgets).
